import = ["~/dotfiles/alacritty-themes/tokyonight_moon.toml"]

[font]
size = 11

[font.bold]
family = "Hack Nerd Font"
style = "Regular"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 30000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = true
opacity = 0.95
blur = true


[window.padding]
x = 6
y = 6
