scan_timeout = 10
command_timeout = 300

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$env_var\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""

[[battery.display]]
threshold = 50

[time]
disabled = false

[git_status]
ignore_submodules = true
